//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MerchantApplicationWebServiceSoap", Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class MerchantApplicationWebService : Microsoft.Web.Services.WebServicesClientProtocol
{
    
    private System.Threading.SendOrPostCallback RetrieveAgreementTextOperationCompleted;
    
    private System.Threading.SendOrPostCallback RetrieveMerchantStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback RetrieveMerchantOperationCompleted;
    
    private System.Threading.SendOrPostCallback SubmitCompletedApplicationOperationCompleted;
    
    private System.Threading.SendOrPostCallback SubmitPartialApplicationOperationCompleted;
    
    /// <remarks/>
    public MerchantApplicationWebService() {
        this.Url = "https://services.innovativemerchant.com/MerchantApplicationWebService_v1_2/Mercha" +
            "ntApplicationWebService.asmx";
    }
    
    /// <remarks/>
    public event RetrieveAgreementTextCompletedEventHandler RetrieveAgreementTextCompleted;
    
    /// <remarks/>
    public event RetrieveMerchantStatusCompletedEventHandler RetrieveMerchantStatusCompleted;
    
    /// <remarks/>
    public event RetrieveMerchantCompletedEventHandler RetrieveMerchantCompleted;
    
    /// <remarks/>
    public event SubmitCompletedApplicationCompletedEventHandler SubmitCompletedApplicationCompleted;
    
    /// <remarks/>
    public event SubmitPartialApplicationCompletedEventHandler SubmitPartialApplicationCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.innovativemerchant.com/MerchantApplicationWebService/RetrieveAgreement" +
        "Text", RequestNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", ResponseNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Agreement[] RetrieveAgreementText(string AgentReferralID) {
        object[] results = this.Invoke("RetrieveAgreementText", new object[] {
                    AgentReferralID});
        return ((Agreement[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRetrieveAgreementText(string AgentReferralID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RetrieveAgreementText", new object[] {
                    AgentReferralID}, callback, asyncState);
    }
    
    /// <remarks/>
    public Agreement[] EndRetrieveAgreementText(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Agreement[])(results[0]));
    }
    
    /// <remarks/>
    public void RetrieveAgreementTextAsync(string AgentReferralID) {
        this.RetrieveAgreementTextAsync(AgentReferralID, null);
    }
    
    /// <remarks/>
    public void RetrieveAgreementTextAsync(string AgentReferralID, object userState) {
        if ((this.RetrieveAgreementTextOperationCompleted == null)) {
            this.RetrieveAgreementTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAgreementTextOperationCompleted);
        }
        this.InvokeAsync("RetrieveAgreementText", new object[] {
                    AgentReferralID}, this.RetrieveAgreementTextOperationCompleted, userState);
    }
    
    private void OnRetrieveAgreementTextOperationCompleted(object arg) {
        if ((this.RetrieveAgreementTextCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RetrieveAgreementTextCompleted(this, new RetrieveAgreementTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.innovativemerchant.com/MerchantApplicationWebService/RetrieveMerchantS" +
        "tatus", RequestNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", ResponseNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int RetrieveMerchantStatus(string ApplicationReferenceID) {
        object[] results = this.Invoke("RetrieveMerchantStatus", new object[] {
                    ApplicationReferenceID});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRetrieveMerchantStatus(string ApplicationReferenceID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RetrieveMerchantStatus", new object[] {
                    ApplicationReferenceID}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndRetrieveMerchantStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void RetrieveMerchantStatusAsync(string ApplicationReferenceID) {
        this.RetrieveMerchantStatusAsync(ApplicationReferenceID, null);
    }
    
    /// <remarks/>
    public void RetrieveMerchantStatusAsync(string ApplicationReferenceID, object userState) {
        if ((this.RetrieveMerchantStatusOperationCompleted == null)) {
            this.RetrieveMerchantStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveMerchantStatusOperationCompleted);
        }
        this.InvokeAsync("RetrieveMerchantStatus", new object[] {
                    ApplicationReferenceID}, this.RetrieveMerchantStatusOperationCompleted, userState);
    }
    
    private void OnRetrieveMerchantStatusOperationCompleted(object arg) {
        if ((this.RetrieveMerchantStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RetrieveMerchantStatusCompleted(this, new RetrieveMerchantStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.innovativemerchant.com/MerchantApplicationWebService/RetrieveMerchant", RequestNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", ResponseNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Merchant RetrieveMerchant(string ApplicationReferenceID) {
        object[] results = this.Invoke("RetrieveMerchant", new object[] {
                    ApplicationReferenceID});
        return ((Merchant)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRetrieveMerchant(string ApplicationReferenceID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RetrieveMerchant", new object[] {
                    ApplicationReferenceID}, callback, asyncState);
    }
    
    /// <remarks/>
    public Merchant EndRetrieveMerchant(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Merchant)(results[0]));
    }
    
    /// <remarks/>
    public void RetrieveMerchantAsync(string ApplicationReferenceID) {
        this.RetrieveMerchantAsync(ApplicationReferenceID, null);
    }
    
    /// <remarks/>
    public void RetrieveMerchantAsync(string ApplicationReferenceID, object userState) {
        if ((this.RetrieveMerchantOperationCompleted == null)) {
            this.RetrieveMerchantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveMerchantOperationCompleted);
        }
        this.InvokeAsync("RetrieveMerchant", new object[] {
                    ApplicationReferenceID}, this.RetrieveMerchantOperationCompleted, userState);
    }
    
    private void OnRetrieveMerchantOperationCompleted(object arg) {
        if ((this.RetrieveMerchantCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RetrieveMerchantCompleted(this, new RetrieveMerchantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.innovativemerchant.com/MerchantApplicationWebService/SubmitCompletedAp" +
        "plication", RequestNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", ResponseNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result SubmitCompletedApplication(MerchantApplication MerchantApplication, AgreementSection AgreementSection) {
        object[] results = this.Invoke("SubmitCompletedApplication", new object[] {
                    MerchantApplication,
                    AgreementSection});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSubmitCompletedApplication(MerchantApplication MerchantApplication, AgreementSection AgreementSection, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SubmitCompletedApplication", new object[] {
                    MerchantApplication,
                    AgreementSection}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndSubmitCompletedApplication(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void SubmitCompletedApplicationAsync(MerchantApplication MerchantApplication, AgreementSection AgreementSection) {
        this.SubmitCompletedApplicationAsync(MerchantApplication, AgreementSection, null);
    }
    
    /// <remarks/>
    public void SubmitCompletedApplicationAsync(MerchantApplication MerchantApplication, AgreementSection AgreementSection, object userState) {
        if ((this.SubmitCompletedApplicationOperationCompleted == null)) {
            this.SubmitCompletedApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitCompletedApplicationOperationCompleted);
        }
        this.InvokeAsync("SubmitCompletedApplication", new object[] {
                    MerchantApplication,
                    AgreementSection}, this.SubmitCompletedApplicationOperationCompleted, userState);
    }
    
    private void OnSubmitCompletedApplicationOperationCompleted(object arg) {
        if ((this.SubmitCompletedApplicationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SubmitCompletedApplicationCompleted(this, new SubmitCompletedApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.innovativemerchant.com/MerchantApplicationWebService/SubmitPartialAppl" +
        "ication", RequestNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", ResponseNamespace="http://www.innovativemerchant.com/MerchantApplicationWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result SubmitPartialApplication(string Password, MerchantApplication MerchantApplication) {
        object[] results = this.Invoke("SubmitPartialApplication", new object[] {
                    Password,
                    MerchantApplication});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSubmitPartialApplication(string Password, MerchantApplication MerchantApplication, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SubmitPartialApplication", new object[] {
                    Password,
                    MerchantApplication}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndSubmitPartialApplication(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void SubmitPartialApplicationAsync(string Password, MerchantApplication MerchantApplication) {
        this.SubmitPartialApplicationAsync(Password, MerchantApplication, null);
    }
    
    /// <remarks/>
    public void SubmitPartialApplicationAsync(string Password, MerchantApplication MerchantApplication, object userState) {
        if ((this.SubmitPartialApplicationOperationCompleted == null)) {
            this.SubmitPartialApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitPartialApplicationOperationCompleted);
        }
        this.InvokeAsync("SubmitPartialApplication", new object[] {
                    Password,
                    MerchantApplication}, this.SubmitPartialApplicationOperationCompleted, userState);
    }
    
    private void OnSubmitPartialApplicationOperationCompleted(object arg) {
        if ((this.SubmitPartialApplicationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SubmitPartialApplicationCompleted(this, new SubmitPartialApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Agreement {
    
    private string descriptionField;
    
    private string textField;
    
    private bool agreeField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public bool Agree {
        get {
            return this.agreeField;
        }
        set {
            this.agreeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class ValidationError {
    
    private string textField;
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Result {
    
    private string applicationReferenceIDField;
    
    private string redirectURLField;
    
    private ValidationError[] validationErrorsField;
    
    /// <remarks/>
    public string ApplicationReferenceID {
        get {
            return this.applicationReferenceIDField;
        }
        set {
            this.applicationReferenceIDField = value;
        }
    }
    
    /// <remarks/>
    public string RedirectURL {
        get {
            return this.redirectURLField;
        }
        set {
            this.redirectURLField = value;
        }
    }
    
    /// <remarks/>
    public ValidationError[] ValidationErrors {
        get {
            return this.validationErrorsField;
        }
        set {
            this.validationErrorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Rate {
    
    private decimal discountRateField;
    
    private decimal monthlyMinimumField;
    
    private decimal transactionFeeField;
    
    private decimal statementFeeField;
    
    private string equipmentField;
    
    private decimal debitTransactionFeeField;
    
    private decimal debitStatementFeeField;
    
    private decimal checkGuaranteeTransactionFeeField;
    
    private decimal checkGuaranteeDiscountRateField;
    
    private string checkGuaranteePlanField;
    
    private decimal gatewayStatementFeeField;
    
    private decimal gatewayTransactionFeeField;
    
    private decimal eBTStatementFeeField;
    
    private decimal eBTTransactionFeeField;
    
    private string eBTIdentificationNumberField;
    
    /// <remarks/>
    public decimal DiscountRate {
        get {
            return this.discountRateField;
        }
        set {
            this.discountRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal MonthlyMinimum {
        get {
            return this.monthlyMinimumField;
        }
        set {
            this.monthlyMinimumField = value;
        }
    }
    
    /// <remarks/>
    public decimal TransactionFee {
        get {
            return this.transactionFeeField;
        }
        set {
            this.transactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal StatementFee {
        get {
            return this.statementFeeField;
        }
        set {
            this.statementFeeField = value;
        }
    }
    
    /// <remarks/>
    public string Equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    public decimal DebitTransactionFee {
        get {
            return this.debitTransactionFeeField;
        }
        set {
            this.debitTransactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal DebitStatementFee {
        get {
            return this.debitStatementFeeField;
        }
        set {
            this.debitStatementFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal CheckGuaranteeTransactionFee {
        get {
            return this.checkGuaranteeTransactionFeeField;
        }
        set {
            this.checkGuaranteeTransactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal CheckGuaranteeDiscountRate {
        get {
            return this.checkGuaranteeDiscountRateField;
        }
        set {
            this.checkGuaranteeDiscountRateField = value;
        }
    }
    
    /// <remarks/>
    public string CheckGuaranteePlan {
        get {
            return this.checkGuaranteePlanField;
        }
        set {
            this.checkGuaranteePlanField = value;
        }
    }
    
    /// <remarks/>
    public decimal GatewayStatementFee {
        get {
            return this.gatewayStatementFeeField;
        }
        set {
            this.gatewayStatementFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal GatewayTransactionFee {
        get {
            return this.gatewayTransactionFeeField;
        }
        set {
            this.gatewayTransactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal EBTStatementFee {
        get {
            return this.eBTStatementFeeField;
        }
        set {
            this.eBTStatementFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal EBTTransactionFee {
        get {
            return this.eBTTransactionFeeField;
        }
        set {
            this.eBTTransactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public string EBTIdentificationNumber {
        get {
            return this.eBTIdentificationNumberField;
        }
        set {
            this.eBTIdentificationNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Representative {
    
    private int representativeIDField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    /// <remarks/>
    public int RepresentativeID {
        get {
            return this.representativeIDField;
        }
        set {
            this.representativeIDField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Agent {
    
    private int agentIDField;
    
    private int programIDField;
    
    private string nameField;
    
    private Representative representativeField;
    
    /// <remarks/>
    public int AgentID {
        get {
            return this.agentIDField;
        }
        set {
            this.agentIDField = value;
        }
    }
    
    /// <remarks/>
    public int ProgramID {
        get {
            return this.programIDField;
        }
        set {
            this.programIDField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public Representative Representative {
        get {
            return this.representativeField;
        }
        set {
            this.representativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class AgreementSection {
    
    private Agreement[] agreementsField;
    
    private bool finalAgreementField;
    
    private string iPAddressField;
    
    /// <remarks/>
    public Agreement[] Agreements {
        get {
            return this.agreementsField;
        }
        set {
            this.agreementsField = value;
        }
    }
    
    /// <remarks/>
    public bool FinalAgreement {
        get {
            return this.finalAgreementField;
        }
        set {
            this.finalAgreementField = value;
        }
    }
    
    /// <remarks/>
    public string IPAddress {
        get {
            return this.iPAddressField;
        }
        set {
            this.iPAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class CardType {
    
    private CardIssuer cardIssuerField;
    
    private CardTypeOptions acceptActionField;
    
    private string accountNumberField;
    
    /// <remarks/>
    public CardIssuer CardIssuer {
        get {
            return this.cardIssuerField;
        }
        set {
            this.cardIssuerField = value;
        }
    }
    
    /// <remarks/>
    public CardTypeOptions AcceptAction {
        get {
            return this.acceptActionField;
        }
        set {
            this.acceptActionField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum CardIssuer {
    
    /// <remarks/>
    AmericanExpress,
    
    /// <remarks/>
    Diners,
    
    /// <remarks/>
    Discover,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum CardTypeOptions {
    
    /// <remarks/>
    DontApply,
    
    /// <remarks/>
    Apply,
    
    /// <remarks/>
    CurrentlyAccept,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Bank {
    
    private string nameField;
    
    private Address addressField;
    
    private string phoneNumberField;
    
    private string routingNumberField;
    
    private string accountNumberField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public Address Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string RoutingNumber {
        get {
            return this.routingNumberField;
        }
        set {
            this.routingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Address {
    
    private string address1Field;
    
    private string address2Field;
    
    private string cityField;
    
    private State stateField;
    
    private string postalCodeField;
    
    /// <remarks/>
    public string Address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public State State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum State {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    AK,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    AZ,
    
    /// <remarks/>
    CA,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    CT,
    
    /// <remarks/>
    DC,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    FL,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    HI,
    
    /// <remarks/>
    IA,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IL,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    KS,
    
    /// <remarks/>
    KY,
    
    /// <remarks/>
    LA,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MD,
    
    /// <remarks/>
    ME,
    
    /// <remarks/>
    MI,
    
    /// <remarks/>
    MN,
    
    /// <remarks/>
    MO,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    ND,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    NH,
    
    /// <remarks/>
    NJ,
    
    /// <remarks/>
    NM,
    
    /// <remarks/>
    NV,
    
    /// <remarks/>
    NY,
    
    /// <remarks/>
    OH,
    
    /// <remarks/>
    OK,
    
    /// <remarks/>
    OR,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    RI,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TX,
    
    /// <remarks/>
    UT,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    VT,
    
    /// <remarks/>
    WA,
    
    /// <remarks/>
    WI,
    
    /// <remarks/>
    WV,
    
    /// <remarks/>
    WY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class CreditCard {
    
    private string cardholderNameField;
    
    private string accountNumberField;
    
    private System.DateTime expirationDateField;
    
    /// <remarks/>
    public string CardholderName {
        get {
            return this.cardholderNameField;
        }
        set {
            this.cardholderNameField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ExpirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Financial {
    
    private CreditCard creditCardField;
    
    private Bank[] banksField;
    
    /// <remarks/>
    public CreditCard CreditCard {
        get {
            return this.creditCardField;
        }
        set {
            this.creditCardField = value;
        }
    }
    
    /// <remarks/>
    public Bank[] Banks {
        get {
            return this.banksField;
        }
        set {
            this.banksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class History {
    
    private bool hadPriorCardAquirerField;
    
    private string priorCardAquirerNameField;
    
    private string priorCardAquirerDepartureReasonField;
    
    private bool terminatedMerchantFileField;
    
    /// <remarks/>
    public bool HadPriorCardAquirer {
        get {
            return this.hadPriorCardAquirerField;
        }
        set {
            this.hadPriorCardAquirerField = value;
        }
    }
    
    /// <remarks/>
    public string PriorCardAquirerName {
        get {
            return this.priorCardAquirerNameField;
        }
        set {
            this.priorCardAquirerNameField = value;
        }
    }
    
    /// <remarks/>
    public string PriorCardAquirerDepartureReason {
        get {
            return this.priorCardAquirerDepartureReasonField;
        }
        set {
            this.priorCardAquirerDepartureReasonField = value;
        }
    }
    
    /// <remarks/>
    public bool TerminatedMerchantFile {
        get {
            return this.terminatedMerchantFileField;
        }
        set {
            this.terminatedMerchantFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Principal {
    
    private int ownershipPercentageField;
    
    private string firstNameField;
    
    private string middleInitialField;
    
    private string lastNameField;
    
    private Suffix suffixField;
    
    private System.DateTime birthDateField;
    
    private string socialSecurityNumberField;
    
    private string driverLicenseNumberField;
    
    private State driverLicenseStateField;
    
    private System.DateTime driverLicenseExpirationDateField;
    
    private string residencePhoneNumberField;
    
    private Address residenceAddressField;
    
    private ResidenceOwnership residenceOwnershipField;
    
    private System.DateTime residenceEstablishmentDateField;
    
    /// <remarks/>
    public int OwnershipPercentage {
        get {
            return this.ownershipPercentageField;
        }
        set {
            this.ownershipPercentageField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleInitial {
        get {
            return this.middleInitialField;
        }
        set {
            this.middleInitialField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public Suffix Suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    public string SocialSecurityNumber {
        get {
            return this.socialSecurityNumberField;
        }
        set {
            this.socialSecurityNumberField = value;
        }
    }
    
    /// <remarks/>
    public string DriverLicenseNumber {
        get {
            return this.driverLicenseNumberField;
        }
        set {
            this.driverLicenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public State DriverLicenseState {
        get {
            return this.driverLicenseStateField;
        }
        set {
            this.driverLicenseStateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DriverLicenseExpirationDate {
        get {
            return this.driverLicenseExpirationDateField;
        }
        set {
            this.driverLicenseExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    public string ResidencePhoneNumber {
        get {
            return this.residencePhoneNumberField;
        }
        set {
            this.residencePhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public Address ResidenceAddress {
        get {
            return this.residenceAddressField;
        }
        set {
            this.residenceAddressField = value;
        }
    }
    
    /// <remarks/>
    public ResidenceOwnership ResidenceOwnership {
        get {
            return this.residenceOwnershipField;
        }
        set {
            this.residenceOwnershipField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ResidenceEstablishmentDate {
        get {
            return this.residenceEstablishmentDateField;
        }
        set {
            this.residenceEstablishmentDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum Suffix {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    Jr,
    
    /// <remarks/>
    Sr,
    
    /// <remarks/>
    II,
    
    /// <remarks/>
    III,
    
    /// <remarks/>
    Esq,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum ResidenceOwnership {
    
    /// <remarks/>
    Rent,
    
    /// <remarks/>
    Own,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class TerminalSectorPercentage {
    
    private int swipedField;
    
    private int keyedWithImprintField;
    
    private int keyedWithoutImprintField;
    
    /// <remarks/>
    public int Swiped {
        get {
            return this.swipedField;
        }
        set {
            this.swipedField = value;
        }
    }
    
    /// <remarks/>
    public int KeyedWithImprint {
        get {
            return this.keyedWithImprintField;
        }
        set {
            this.keyedWithImprintField = value;
        }
    }
    
    /// <remarks/>
    public int KeyedWithoutImprint {
        get {
            return this.keyedWithoutImprintField;
        }
        set {
            this.keyedWithoutImprintField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class BusinessSectorPercentage {
    
    private int retailField;
    
    private int restaurantField;
    
    private int serviceField;
    
    private int mailPhoneOrderField;
    
    private int internetField;
    
    private int otherField;
    
    /// <remarks/>
    public int Retail {
        get {
            return this.retailField;
        }
        set {
            this.retailField = value;
        }
    }
    
    /// <remarks/>
    public int Restaurant {
        get {
            return this.restaurantField;
        }
        set {
            this.restaurantField = value;
        }
    }
    
    /// <remarks/>
    public int Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    public int MailPhoneOrder {
        get {
            return this.mailPhoneOrderField;
        }
        set {
            this.mailPhoneOrderField = value;
        }
    }
    
    /// <remarks/>
    public int Internet {
        get {
            return this.internetField;
        }
        set {
            this.internetField = value;
        }
    }
    
    /// <remarks/>
    public int Other {
        get {
            return this.otherField;
        }
        set {
            this.otherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Business {
    
    private string legalNameField;
    
    private string dBAField;
    
    private Address locationAddressField;
    
    private Address mailAddressField;
    
    private string phoneNumberField;
    
    private string faxNumberField;
    
    private string uRLField;
    
    private string federalTaxIDField;
    
    private BusinessType typeField;
    
    private System.DateTime establishmentDateField;
    
    private string productLineField;
    
    private BusinessSectorPercentage businessSectorPercentageField;
    
    private TerminalSectorPercentage terminalSectorPercentageField;
    
    private decimal averageSaleAmountField;
    
    private decimal averageMonthlyVolumeField;
    
    /// <remarks/>
    public string LegalName {
        get {
            return this.legalNameField;
        }
        set {
            this.legalNameField = value;
        }
    }
    
    /// <remarks/>
    public string DBA {
        get {
            return this.dBAField;
        }
        set {
            this.dBAField = value;
        }
    }
    
    /// <remarks/>
    public Address LocationAddress {
        get {
            return this.locationAddressField;
        }
        set {
            this.locationAddressField = value;
        }
    }
    
    /// <remarks/>
    public Address MailAddress {
        get {
            return this.mailAddressField;
        }
        set {
            this.mailAddressField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string FaxNumber {
        get {
            return this.faxNumberField;
        }
        set {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    public string FederalTaxID {
        get {
            return this.federalTaxIDField;
        }
        set {
            this.federalTaxIDField = value;
        }
    }
    
    /// <remarks/>
    public BusinessType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EstablishmentDate {
        get {
            return this.establishmentDateField;
        }
        set {
            this.establishmentDateField = value;
        }
    }
    
    /// <remarks/>
    public string ProductLine {
        get {
            return this.productLineField;
        }
        set {
            this.productLineField = value;
        }
    }
    
    /// <remarks/>
    public BusinessSectorPercentage BusinessSectorPercentage {
        get {
            return this.businessSectorPercentageField;
        }
        set {
            this.businessSectorPercentageField = value;
        }
    }
    
    /// <remarks/>
    public TerminalSectorPercentage TerminalSectorPercentage {
        get {
            return this.terminalSectorPercentageField;
        }
        set {
            this.terminalSectorPercentageField = value;
        }
    }
    
    /// <remarks/>
    public decimal AverageSaleAmount {
        get {
            return this.averageSaleAmountField;
        }
        set {
            this.averageSaleAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal AverageMonthlyVolume {
        get {
            return this.averageMonthlyVolumeField;
        }
        set {
            this.averageMonthlyVolumeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public enum BusinessType {
    
    /// <remarks/>
    SoleProprietorship,
    
    /// <remarks/>
    Partnership,
    
    /// <remarks/>
    LimitedLiabilityCorporation,
    
    /// <remarks/>
    Corporation,
    
    /// <remarks/>
    NonProfitOrganization,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class MerchantApplication {
    
    private string emailAddressField;
    
    private string agentReferralIDField;
    
    private string externalAgentUserIDField;
    
    private Business businessField;
    
    private Principal[] principalsField;
    
    private History historyField;
    
    private Financial financialField;
    
    private CardType[] cardTypesField;
    
    /// <remarks/>
    public string EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    public string AgentReferralID {
        get {
            return this.agentReferralIDField;
        }
        set {
            this.agentReferralIDField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalAgentUserID {
        get {
            return this.externalAgentUserIDField;
        }
        set {
            this.externalAgentUserIDField = value;
        }
    }
    
    /// <remarks/>
    public Business Business {
        get {
            return this.businessField;
        }
        set {
            this.businessField = value;
        }
    }
    
    /// <remarks/>
    public Principal[] Principals {
        get {
            return this.principalsField;
        }
        set {
            this.principalsField = value;
        }
    }
    
    /// <remarks/>
    public History History {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    public Financial Financial {
        get {
            return this.financialField;
        }
        set {
            this.financialField = value;
        }
    }
    
    /// <remarks/>
    public CardType[] CardTypes {
        get {
            return this.cardTypesField;
        }
        set {
            this.cardTypesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.innovativemerchant.com/MerchantApplicationWebService/")]
public partial class Merchant {
    
    private string applicationReferenceIDField;
    
    private System.DateTime applicationStartDateField;
    
    private System.DateTime applicationEndDateField;
    
    private MerchantApplication merchantApplicationField;
    
    private int merchantStatusField;
    
    private int lastPageCompletedField;
    
    private System.DateTime lastPageCompletedDateField;
    
    private AgreementSection agreementSectionField;
    
    private Agent agentField;
    
    private Rate rateField;
    
    /// <remarks/>
    public string ApplicationReferenceID {
        get {
            return this.applicationReferenceIDField;
        }
        set {
            this.applicationReferenceIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ApplicationStartDate {
        get {
            return this.applicationStartDateField;
        }
        set {
            this.applicationStartDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ApplicationEndDate {
        get {
            return this.applicationEndDateField;
        }
        set {
            this.applicationEndDateField = value;
        }
    }
    
    /// <remarks/>
    public MerchantApplication MerchantApplication {
        get {
            return this.merchantApplicationField;
        }
        set {
            this.merchantApplicationField = value;
        }
    }
    
    /// <remarks/>
    public int MerchantStatus {
        get {
            return this.merchantStatusField;
        }
        set {
            this.merchantStatusField = value;
        }
    }
    
    /// <remarks/>
    public int LastPageCompleted {
        get {
            return this.lastPageCompletedField;
        }
        set {
            this.lastPageCompletedField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastPageCompletedDate {
        get {
            return this.lastPageCompletedDateField;
        }
        set {
            this.lastPageCompletedDateField = value;
        }
    }
    
    /// <remarks/>
    public AgreementSection AgreementSection {
        get {
            return this.agreementSectionField;
        }
        set {
            this.agreementSectionField = value;
        }
    }
    
    /// <remarks/>
    public Agent Agent {
        get {
            return this.agentField;
        }
        set {
            this.agentField = value;
        }
    }
    
    /// <remarks/>
    public Rate Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void RetrieveAgreementTextCompletedEventHandler(object sender, RetrieveAgreementTextCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RetrieveAgreementTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RetrieveAgreementTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Agreement[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Agreement[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void RetrieveMerchantStatusCompletedEventHandler(object sender, RetrieveMerchantStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RetrieveMerchantStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RetrieveMerchantStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void RetrieveMerchantCompletedEventHandler(object sender, RetrieveMerchantCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RetrieveMerchantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RetrieveMerchantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Merchant Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Merchant)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SubmitCompletedApplicationCompletedEventHandler(object sender, SubmitCompletedApplicationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubmitCompletedApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SubmitCompletedApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SubmitPartialApplicationCompletedEventHandler(object sender, SubmitPartialApplicationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SubmitPartialApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SubmitPartialApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}
